name: Build & Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.x'
      - run: npm ci
      - run: npm run build
      - name: Setup git
        run: |
          git config --global advice.addIgnoredFile false
          git config --global user.name "DevTrackap"
          git config --global user.email "dev@trackap.com"
      - run: git add ./dist/*
      - run: git commit -am "Build [skip ci]"
      - run: git push