name: Build & Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.x'
      - run: npm ci
      - run: npm run build
      - run: git add ./dist/*
      - run: git commit -am "Build [skip ci]"
      - run: git push